FR-10-nuevas-rutas
gabriromero/front-pokemon-league pull request #20
Opened 2023-03-27 21:09 UTC by TheJohniX

terminado el componente de las nuevas rutas :)

2023-03-27 22:37 UTC, danielavdalian commented on src/components/NuevasRutas.vue
> +        <div class="row divRutas">
Cuando la resolución hace que una línea compuesta por dos palabras tenga que hacer un salto de línea, reserva un salto también para la otra "columna"
![image](https://user-images.githubusercontent.com/78348541/228082379-49151624-30c3-47ab-8b06-014571eb511e.png)

2023-03-27 22:43 UTC, danielavdalian requested changes
El tema del salto de línea. Si en alguna jornada pasa un par de veces o tres en la primera columna, la segunda quedará con saltos de línea incoherentes

2023-03-28 21:04 UTC, TheJohniX commented
hola buenas noches, ya lo he arreglado acéptenme la pr porfavor o lloro

2023-03-28 23:45 UTC, gabriromero approved these changes
De chill pa dentro 🤑 💯

2023-04-01 21:05 UTC, danielavdalian approved these changes

2023-04-01 22:34 UTC, merged