Added Profile Logic
gabriromero/front-pokemon-league pull request #43
Opened 2023-04-20 09:15 UTC by danielavdalian

2023-04-20 16:32 UTC, gabriromero requested changes
El funcionamiento está perf.
Lo único arreglar los apuntes 🫡

2023-04-20 16:32 UTC, gabriromero commented on src/components/ProfileStats.vue
> +      <span class="text-container num"> {{combatesJugados-combatesGanados}}</span>
Condición mal hecha

2023-04-20 16:32 UTC, gabriromero commented on src/views/PerfilView.vue
> +      let hoy = new Date();
Prueba a dar un valor a la variable **hoy** para comprobar si realmente hace bien el cálculo de dias

Spoiler: Lo hace mal

2023-04-20 16:32 UTC, gabriromero commented on src/components/Selector.vue
> +  <div v-if="middle" class="perfil">
Este if es una mejor solución que dejarlo sin nada ya que evita que aparezca la skin por defecto y después se cambie (efecto muy Perú) pero igualmente queda medio raro ya que aparece un espacio en blanco y luego se renderiza de golpe.

Te propongo dos mejores soluciones:
1. Crear un booleano skinsLoaded que por defecto será false. Al terminar la llamada del put, se seteará a true.
En cada uno de los tags img que tengan la skin, tendrá que aplicarle el v-if="skinsLoaded"

2. Añadir un nuevo asset trainer-0.jpg que será una skin modificada para que no tenga cara (hará la función de simular que se está cargando). Luego será cuestión de setear las skins por defecto a trainer-0.jpg y no hará falta ningun v-if.

2023-04-20 20:59 UTC, danielavdalian commented on src/views/PerfilView.vue
> +      let hoy = new Date();
![image](https://user-images.githubusercontent.com/78348541/233486315-419e6ddb-ce2c-4435-8fbc-ea9ca3525425.png)
No estoy entendiendo, creo que no lo veo

2023-04-20 21:13 UTC, gabriromero commented on src/views/PerfilView.vue
> +      let hoy = new Date();
Ahora lo ves?

const horarios_jornada = [
    [new Date(2023, 4, 1), new Date(2023, 4, 7)],
    [new Date(2023, 4, 8), new Date(2023, 4, 14)],
    [new Date(2023, 4, 15), new Date(2023, 4, 21)],
    [new Date(2023, 4, 22), new Date(2023, 4, 28)],
    [new Date(2023, 4, 29), new Date(2023, 5, 4)],
    [new Date(2023, 5, 5), new Date(2023, 5, 18)],
    [new Date(2023, 5, 19), new Date(2023, 6, 2)],
    [new Date(2023, 6, 3), new Date(2023, 6, 16)],
    [new Date(2023, 6, 17), new Date(2023, 6, 23)],
];

2023-04-25 16:11 UTC, TheJohniX approved these changes
De malditos locos Daniel. PERFF

2023-04-25 17:55 UTC, gabriromero approved these changes
La solución del spinner más clean que las propuestas que te he sugerido 👏
Gj!

2023-04-25 17:55 UTC, merged